name: medverse_mobile_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: any
  font_awesome_flutter: any
  flutter_svg: any
  page_transition: any
  intro_views_flutter: any
  carousel_slider: ^4.1.1
  # test: any

  #Dialog
  simple_animations: any
  flare_flutter: any
  top_snackbar_flutter: ^1.1.1
  #Gird View card
  flutter_layout_grid: any
  flutter_staggered_grid_view: any
  flutter_lints: any

  #Firebase Dependencies
  cloud_firestore: any
  firebase: any
  firebase_auth: any
  firebase_core: any
  firebase_storage: any
  firebase_analytics: any
  fluttertoast: any
  unicons: any
  timeago: any
  intl: ^0.17.0

  #State Management
  flutter_bloc: any
  image_picker: any
  image_cropper: any

  #Hive DB and SQLite DB
  path: any
  bloc: any
  equatable: any
  http: ^0.13.4 
  sqflite: any
  sqlite3: any

  #Animation
  shimmer_animation: any
  animations: any
  expandable: any
  flutter_neumorphic: ^3.2.0

  get: any
  google_sign_in: any
  flutter_icons: any
  percent_indicator: any
  cached_network_image: any
  flutter_spinkit: any
  image: any
  uuid: any
  path_provider: any
  geolocator: any
  geocoding: any
  google_fonts: any
  provider: any
  modal_progress_hud: any
  shared_preferences: any
  data_connection_checker: any
  flutter_slidable: any
  flutter_typeahead: any
  analyzer: 
  translator: any
  # google_translator: ^1.0.0

dev_dependencies:
  integration_test:
    sdk: flutter
  test: any

  flutter_test:
    sdk: flutter
  mockito: any
  build_runner: any


flutter_launcher_name:
  name: "medverse_mobile_app"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/300_imagenlm/
    - assets/image/300_imagesrxnav/
    - assets/flare/
    - database/Glossary.sqlite
    - database/drugbank.sqlite3
    - assets/images/
    - assets/images/splash/Medverse.png
    - assets/health_profile_icon/

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Lato-Regular
       fonts:
         - asset: assets/fonts/Lato-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
     - family: Roboto-Regular
       fonts:
         - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
     - family: Ubuntu-Regular
       fonts:
         - asset: assets/fonts/Ubuntu-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
